# Use postgres/example user/password credentials
version: '3.7'

services:
  # PGPASSWORD=$POSTGRES_PASSWORD psql -h $HOSTNAME -U $POSTGRES_USER $POSTGRES_DB
  db:
    image: mdillon/postgis:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bcarm
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    volumes:
       - ./openshift/postgis-config/secrets:/run/secrets
       - ./openshift/postgis-config/data:/var/lib/postgresql/data
       - ./openshift/postgis-config/initdb:/docker-entrypoint-initdb.d

  web:
    image: nginx:1.17
    volumes:
    - ./openshift/nginx-config/bcarm.template:/etc/nginx/conf.d/bcarm.template
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=bcarm.local
    - NGINX_PORT=80
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/bcarm.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
    - db

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080