version: '3'

services:

  web:
    image: arm-bc-web:latest
    container_name: arm-bc-web
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    # command: bash "prod_run.sh"

    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"

    env_file:
      - .env
      
    environment:
      ENVIRONMENT: dev
      DEBUG: 'False'
      LOGGER_LEVEL: WARNING
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_EMAIL: ${DEFAULT_EMAIL}
      DEFAULT_FROM_EMAIL: ${DEFAULT_EMAIL}
      EMAIL_TO: ${DEFAULT_EMAIL}
      SERVER_EMAIL: ${DEFAULT_EMAIL}
      SUPPORT_EMAIL: ${DEFAULT_EMAIL}
      WEASYPRINT_URL: ${WEASYPRINT_URL}
