version: '2'

services:

  db:
    image: postgres 
    container_name: arm-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_NAME}
      POSTGRES_DB: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    env_file:
      - .env

  web:
    image: arm-bc-web:latest
    container_name: arm-bc-web
    build: .
    #command: bash -c "./manage.py collectstatic --no-input;./manage.py migrate; ./manage.py loaddata initial_data; gunicorn arm.wsgi -b 0.0.0.0:5000"

    stdin_open: true
    tty: true
    
    volumes:
      - .:/code
      - static_volume:/static   

    env_file:
      - .env
      
    environment:
      DEBUG: 'False'
      LOGGER_LEVEL: WARNING
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_EMAIL: ${DEFAULT_EMAIL}
      DEFAULT_FROM_EMAIL: ${DEFAULT_EMAIL}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      SERVER_EMAIL: ${DEFAULT_EMAIL}
      SUPPORT_EMAIL: ${DEFAULT_EMAIL}
      WEASYPRINT_URL: ${WEASYPRINT_URL}

    depends_on:
    - db      

  nginx:
    image: nginx:1.17
    container_name: arm-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static_volume:/static   
    depends_on:
      - web

volumes:
  static_volume: